Feature: Info Page
KnightHacks/hackathon-app-2021 pull request #24
Opened 2021-09-15 00:48 UTC by NelsonJTSM

https://github.com/KnightHacks/hackathon-app-2021/issues/9

2021-09-15 01:07 UTC, suneettipirneni requested changes
Looks good overall, just some minor changes.

2021-09-15 01:08 UTC, suneettipirneni requested changes
Looks good overall, just some minor changes.

2021-09-15 01:08 UTC, suneettipirneni commented on src/components/cards/SocialCard.tsx
> +export type Social = {
use an `interface` instead of a `type` here.

2021-09-15 01:08 UTC, suneettipirneni commented on src/components/cards/SocialCard.tsx
> +  type: string;
You can declare an `enum` representing the possible values for the `type` field:

```ts
enum SocialTypes {
  Discord,
  Website,
  Facebook,
  Instagram,
  Twitter,
}
```

Then set the `type` to be any of the keys from that enum:
```suggestion
  type: keyof SocialTypes;
```

2021-09-15 01:08 UTC, suneettipirneni commented on src/components/cards/SocialCard.tsx
> +  logo: any;
I don't think logo should be `any` it should probably be `JSX.Element`

2021-09-15 19:39 UTC, NelsonJTSM commented
Minor changes have been pushed.

2021-09-16 00:34 UTC, suneettipirneni approved these changes
Lgtm

2021-09-16 14:55 UTC, merged